# Super Node Configuration for Synthron Blockchain

# [General]
# General node settings
node_name = "super_node_1"
node_type = "super"
log_level = "info"
data_dir = "/var/lib/super_node/data"
log_dir = "/var/lib/super_node/logs"

# [Network]
# Network settings
network_id = "synthron_mainnet"
listen_address = "0.0.0.0:8080"
advertise_address = "your_public_ip:8080"

# [Database]
# Database settings
db_path = "/var/lib/super_node/data/blockchain.db"
db_type = "leveldb"
db_cache_size = "2GB"

# [Storage]
# Storage settings for managing large datasets
storage_dir = "/var/lib/super_node/storage"
storage_max_size = "10TB"

# [Performance]
# Performance tuning settings
max_connections = 1000
max_inbound_connections = 800
max_outbound_connections = 200

# [Security]
# Security settings
enable_tls = true
tls_cert_file = "/etc/super_node/tls/server.crt"
tls_key_file = "/etc/super_node/tls/server.key"
firewall_rules = "/etc/super_node/firewall/rules.conf"
intrusion_detection = true

# [Encryption]
# Encryption settings
encryption_algorithm = "AES"
encryption_key_path = "/etc/super_node/encryption/keyfile"

# [SmartContracts]
# Smart contract execution settings
sc_execution_threads = 16
sc_memory_limit = "32GB"
sc_timeout = "300s"

# [Privacy]
# Advanced privacy settings
enable_privacy_protocols = true
privacy_protocol = "zk-snarks"
privacy_key_path = "/etc/super_node/privacy/keyfile"

# [Monitoring]
# Monitoring and uptime settings
monitoring_enabled = true
monitoring_endpoint = "http://localhost:9090"
alerting_endpoint = "http://localhost:9091"
uptime_target = "99.99%"

# [Backup]
# Backup and recovery settings
backup_enabled = true
backup_dir = "/var/lib/super_node/backup"
backup_frequency = "24h"
backup_retention = "7d"

# [Update]
# Update settings for automated updates
update_check_frequency = "12h"
auto_update = true

# [Logging]
# Logging settings
log_rotation = true
log_rotation_size = "100MB"
log_retention = "30d"

# [P2P]
# P2P network settings
p2p_port = 30303
p2p_bootstrap_nodes = [
    "node1.synthron.network:30303",
    "node2.synthron.network:30303",
    "node3.synthron.network:30303"
]

# [Consensus]
# Consensus settings
consensus_algorithm = "proof_of_stake"
consensus_timeout = "5s"
stake_amount = "10000 SYN"

# [Metrics]
# Metrics collection settings
metrics_enabled = true
metrics_port = 9100
metrics_collect_frequency = "60s"

# [Logging]
# Additional logging configurations
log_file = "/var/lib/super_node/logs/super_node.log"
log_format = "json"

# [Advanced]
# Advanced settings
experimental_features_enabled = false
custom_settings = """
# Custom settings can be added here
"""
