# Gateway Node Configuration

[node]
id = "gateway-node-1"
address = "0.0.0.0:8080"

[security]
private_key_path = "/etc/gateway_node/keys/private.key"
public_key_path = "/etc/gateway_node/keys/public.key"
encryption_method = "AES-GCM"
authentication_method = "Argon2"

[network]
max_connections = 1000
read_timeout = "30s"
write_timeout = "30s"
enable_ssl = true
ssl_cert_path = "/etc/gateway_node/ssl/cert.pem"
ssl_key_path = "/etc/gateway_node/ssl/key.pem"

[storage]
data_directory = "/var/lib/gateway_node/data"
log_directory = "/var/log/gateway_node"
max_log_size = "100MB"
max_log_backups = 5
max_log_age = 30

[protocols]
supported_protocols = ["ethereum", "bitcoin", "solana"]
default_protocol = "ethereum"

[external_data]
integration_endpoints = ["https://api.externaldata.com", "https://iot.device.com"]

[performance]
cpu_cores = 8
memory_limit = "128GB"
storage_limit = "10TB"

[security_audits]
audit_frequency = "monthly"
third_party_auditor = "SecureAuditCo"

[authentication]
enable_mfa = true
mfa_methods = ["TOTP", "SMS"]

# Define the mining settings if applicable
[mining]
algorithm = "argon2"
difficulty = "medium"
mining_pool = "https://miningpool.synthron.com"

# Define Proof of History settings
[proof_of_history]
algorithm = "argon2"
history_depth = 1000

# Miscellaneous settings
[misc]
debug_mode = false
node_description = "Primary Gateway Node for Synthron Blockchain"
