# Synthron Archival Full Node Configuration File

# General Settings
[node]
node_type = "archival"  # Node type (archival or pruned)
data_dir = "/var/synthron/data"  # Directory for blockchain data
log_dir = "/var/synthron/logs"  # Directory for log files
log_level = "info"  # Logging level (trace, debug, info, warn, error, fatal)

# Network Settings
[network]
listen_addr = "0.0.0.0:30303"  # Address to listen for incoming connections
external_addr = "0.0.0.0:30303"  # External address for this node
max_peers = 50  # Maximum number of peers to connect with
nat = "any"  # NAT traversal mechanism (none, any, upnp, pmp, extip:<IP>)
p2p_secret_key = "/var/synthron/keys/p2p_secret.key"  # Path to the P2P secret key

# Consensus Settings
[consensus]
engine = "argon2"  # Consensus engine (argon2, scrypt)
pow_target_spacing = 600  # Time between blocks in seconds
difficulty_adjustment_interval = 2016  # Interval for difficulty adjustment

# RPC Settings
[rpc]
http_endpoint = "127.0.0.1:8545"  # HTTP-RPC server endpoint
ws_endpoint = "127.0.0.1:8546"  # WebSocket-RPC server endpoint
http_cors = ["*"]  # Allowed CORS origins
http_hosts = ["localhost"]  # Allowed HTTP hosts
rpc_modules = ["web3", "eth", "net", "debug", "admin", "personal"]  # Enabled RPC modules

# Sync Settings
[sync]
mode = "fast"  # Sync mode (full, fast, light)
snapshot = true  # Enable state snapshots for fast sync

# Database Settings
[database]
db_dir = "/var/synthron/database"  # Directory for the database files
cache_size = 4096  # Cache size in MB
handles = 1000  # Number of file handles to use

# Security Settings
[security]
use_tls = true  # Enable TLS for network communication
tls_cert_file = "/var/synthron/keys/tls_cert.pem"  # Path to TLS certificate
tls_key_file = "/var/synthron/keys/tls_key.pem"  # Path to TLS key
firewall_enabled = true  # Enable firewall
firewall_rules_file = "/var/synthron/config/firewall_rules.toml"  # Path to firewall rules file

# Monitoring and Metrics
[metrics]
enabled = true  # Enable metrics collection
prometheus_endpoint = "127.0.0.1:9090"  # Prometheus metrics endpoint
metrics_prefix = "synthron_"  # Prefix for metrics

# Backup Settings
[backup]
backup_dir = "/var/synthron/backup"  # Directory for backups
backup_interval = "24h"  # Interval between backups
backup_retention = "30d"  # Retention period for backups

# Staking Settings
[staking]
stake_amount = 1000000  # Minimum stake amount in Synthron tokens
reward_address = "0xYourRewardAddress"  # Address for receiving rewards

# API Settings
[api]
enabled = true  # Enable API access
api_endpoint = "127.0.0.1:8080"  # API server endpoint
api_keys = [ "your_api_key" ]  # List of API keys for access control

# Additional Features
[features]
enable_advanced_logging = true  # Enable advanced logging features
enable_predictive_analytics = true  # Enable predictive analytics
enable_anomaly_detection = true  # Enable anomaly detection

# Performance Tuning
[performance]
cache_settings = "default"  # Cache settings (default, optimized)
db_optimization = "high"  # Database optimization level (low, medium, high)

# Developer Options
[developer]
debug_mode = false  # Enable debug mode
testnet = false  # Connect to the testnet instead of the mainnet

