data:
  training_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/training_data.csv'
  validation_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/validation_data.csv'
  test_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/test_data.csv'

model:
  max_len: 128

training_params:
  num_epochs: 20

evaluation:
  save_best_model_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/models/best_model.pth'
