personalization:
  user_data_storage:
    backend: "mongo_db"
    mongo_db:
      connection_string: "mongodb://localhost:27017"
      database_name: "synnergy_network"
      collection_name: "user_preferences"
    redis:
      host: "localhost"
      port: 6379
      db: 0
    storage_strategy: "mongo_db"  # Options: "mongo_db", "redis"

  preference_management:
    update_frequency: "real_time"  # Options: "real_time", "batch"
    max_preferences_per_user: 100

  response_generation:
    personalization_enabled: true
    adaptation_rate: 0.1
    tone_style_customization:
      enable_tone_style: true
      tone_styles:
        - "formal"
        - "casual"
        - "friendly"
        - "professional"

  adaptive_learning:
    enable_adaptive_learning: true
    learning_rate: 0.01
    user_feedback_incorporation: "immediate"  # Options: "immediate", "batch"
    min_interactions_for_learning: 5

  security:
    encryption:
      enable_encryption: true
      algorithm: "AES256"
      key: "your-encryption-key"
    access_control:
      enable_access_control: true
      allowed_roles:
        - "admin"
        - "ml_engineer"
        - "data_scientist"
      read_only_roles:
        - "support"
        - "viewer"
    data_anonymization:
      enable_anonymization: true
      fields_to_anonymize:
        - "user_id"
        - "email"

  retention_policy:
    enable_retention: true
    retention_period_days: 365

  personalization_algorithms:
    collaborative_filtering:
      enabled: true
      neighbors: 10
    content_based:
      enabled: true
      feature_extraction_method: "tf-idf"
    hybrid:
      enabled: true
      weight_collaborative_filtering: 0.6
      weight_content_based: 0.4

  performance_metrics:
    track_metrics: true
    metrics:
      - "response_time"
      - "user_satisfaction"
      - "accuracy"
      - "engagement_rate"
    report_frequency: "daily"

  logging_and_monitoring:
    enable_logging: true
    log_level: "INFO"
    log_to_file: true
    log_file_path: "/var/log/synnergy_network/personalization.log"
    enable_monitoring: true
    monitoring_interval: 60  # in seconds
    alert_thresholds:
      response_time_ms: 1000
      error_rate_percent: 5
      satisfaction_score: 80
