model_config:
  model_name: SynnergyBot
  model_version: 1.0
  model_type: transformer
  num_layers: 24
  hidden_size: 1024
  num_attention_heads: 16
  intermediate_size: 4096
  max_position_embeddings: 2048
  vocab_size: 30522
  dropout_rate: 0.1
  attention_dropout_rate: 0.1
  activation_function: gelu
  learning_rate: 5e-5
  weight_decay: 0.01
  batch_size: 32
  num_epochs: 20
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  warmup_steps: 1000
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-8

training_config:
  data_path: /Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data
  save_path: /Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/models
  log_path: /Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/logs
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1000
  logging_steps: 200
  save_total_limit: 5

context_management_config:
  session_timeout: 300
  context_window_size: 10
  context_storage: redis
  redis_host: localhost
  redis_port: 6379

personalization_config:
  enable_personalization: true
  user_data_storage: sql
  sql_database_url: sqlite:///personalization.db
  personalization_features: [interaction_history, user_preferences, feedback]

security_config:
  use_ssl: true
  encryption_algorithm: AES-256
  data_anonymization: true
  access_control: RBAC
  multi_factor_authentication: true
  security_audit_frequency: monthly

logging_monitoring_config:
  enable_logging: true
  log_level: info
  log_format: "[%(asctime)s] %(levelname)s: %(message)s"
  log_file: bot.log
  enable_monitoring: true
  monitoring_frequency: 60
  alert_thresholds: {error_rate: 0.01, response_time: 2000}
  alert_recipients: ["admin@synnergy.network"]

deployment_config:
  deployment_environment: production
  auto_scaling: true
  load_balancing: true
  max_instances: 10
  min_instances: 2
  health_check_interval: 30
  deployment_region: us-west-1

model_storage_config:
  model_storage_type: local
  local_storage_path: /Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/models
  cloud_storage_url: null
