# Model Storage Configuration

storage:
  type: "cloud"  # Options: "local", "cloud"
  local:
    base_path: "/Users/admin/Desktop/synnergy_network/models"
    model_file_format: "pth"  # Options: "pth", "bin"
  cloud:
    provider: "aws"  # Options: "aws", "gcp", "azure"
    aws:
      s3_bucket: "synnergy-network-models"
      access_key: "your_aws_access_key"
      secret_key: "your_aws_secret_key"
      region: "us-west-2"
    gcp:
      gcs_bucket: "synnergy-network-models"
      credentials_file: "/path/to/gcp/credentials.json"
    azure:
      container: "synnergy-network-models"
      account_name: "your_account_name"
      account_key: "your_account_key"

versioning:
  enabled: true
  strategy: "timestamp"  # Options: "timestamp", "semantic"
  semantic_version:
    major: 1
    minor: 0
    patch: 0

encryption:
  enabled: true
  algorithm: "AES-256"
  key_management:
    type: "kms"  # Options: "kms", "custom"
    kms:
      provider: "aws"  # Options: "aws", "gcp", "azure"
      aws:
        key_id: "your_aws_kms_key_id"
      gcp:
        key_name: "projects/your-project/locations/global/keyRings/your-keyring/cryptoKeys/your-key"
      azure:
        key_vault_url: "https://your-key-vault.vault.azure.net/"
    custom:
      encryption_key: "your_custom_encryption_key"

backup:
  enabled: true
  frequency: "daily"  # Options: "hourly", "daily", "weekly"
  retention_period: "30d"
  location:
    type: "cloud"  # Options: "local", "cloud"
    local:
      base_path: "/Users/admin/Desktop/synnergy_network/backups"
    cloud:
      provider: "aws"  # Options: "aws", "gcp", "azure"
      aws:
        s3_bucket: "synnergy-network-backups"
        access_key: "your_aws_access_key"
        secret_key: "your_aws_secret_key"
        region: "us-west-2"
      gcp:
        gcs_bucket: "synnergy-network-backups"
        credentials_file: "/path/to/gcp/credentials.json"
      azure:
        container: "synnergy-network-backups"
        account_name: "your_account_name"
        account_key: "your_account_key"

compression:
  enabled: true
  algorithm: "gzip"  # Options: "gzip", "lz4", "zstd"

logging:
  enabled: true
  level: "INFO"  # Options: "DEBUG", "INFO", "WARN", "ERROR"
  log_path: "/Users/admin/Desktop/synnergy_network/logs/model_storage.log"

monitoring:
  enabled: true
  frequency: "5m"  # Options: "1m", "5m", "10m", "30m"
  alerting:
    enabled: true
    thresholds:
      error_rate: 5  # percentage
      latency: 1000  # milliseconds
    notification:
      type: "email"  # Options: "email", "sms", "webhook"
      email:
        recipients:
          - "admin@synnergy_network.com"
          - "devops@synnergy_network.com"
      sms:
        phone_numbers:
          - "+1234567890"
      webhook:
        url: "https://your-webhook-url.com/notify"

access_control:
  enabled: true
  roles:
    - name: "admin"
      permissions:
        - "read"
        - "write"
        - "delete"
    - name: "devops"
      permissions:
        - "read"
        - "write"
    - name: "viewer"
      permissions:
        - "read"

compliance:
  enabled: true
  regulations:
    - "GDPR"
    - "CCPA"
    - "HIPAA"
  audit:
    frequency: "annually"  # Options: "monthly", "quarterly", "annually"
    auditor: "external"  # Options: "internal", "external"

metadata:
  model_name: "SynnergyAI"
  description: "Advanced AI Conversation Bot Model for the Synnergy Network"
  tags:
    - "AI"
    - "ConversationBot"
    - "NLP"
  author: "Synnergy Development Team"
  version: "1.0.0"
  created_at: "2024-06-25"
  updated_at: "2024-06-25"
  license: "MIT"
  documentation_url: "https://docs.synnergy_network.com/models/synnergy_ai"
  contact:
    email: "support@synnergy_network.com"
    phone: "+1234567890"
    address: "123 Synnergy Lane, Blockchain City, BC 12345"

