training:
  data:
    train_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/training_data.csv'
    validation_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/validation_data.csv'
    test_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/test_data.csv'
    batch_size: 32
    num_workers: 4
    data_augmentation: 
      enable: true
      techniques: 
        - noise_injection
        - synonym_replacement
        - random_insertion
        - random_deletion

  model:
    architecture: transformer
    num_layers: 12
    hidden_size: 768
    num_attention_heads: 12
    intermediate_size: 3072
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    initializer_range: 0.02
    layer_norm_eps: 1e-12
    use_pretrained_embeddings: false

  training_params:
    learning_rate: 3e-5
    weight_decay: 0.01
    num_epochs: 10
    gradient_accumulation_steps: 1
    max_grad_norm: 1.0
    warmup_steps: 1000
    optimizer: AdamW
    scheduler: linear
    early_stopping:
      enable: true
      patience: 3
      monitor: 'val_loss'

  evaluation:
    metrics: 
      - accuracy
      - precision
      - recall
      - f1_score
    save_best_model: true
    save_best_model_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/models/best_model.pt'

  logging:
    log_interval: 10
    log_dir: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/logs'
    tensorboard: true

  checkpoints:
    enable_checkpoints: true
    checkpoint_interval: 100
    checkpoint_dir: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/checkpoints'

  distributed_training:
    enable_distributed: true
    backend: 'nccl'
    num_gpus: 4

  seed: 42
  fp16:
    enable: true
    opt_level: 'O1'

  data_splitting:
    train_split: 0.8
    validation_split: 0.1
    test_split: 0.1

data:
  training_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/training_data.csv'
  validation_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/validation_data.csv'
  test_data_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/data/test_data.csv'

augmentation:
  alpha_sr: 0.1  # percentage of words to be replaced by synonyms
  alpha_ri: 0.1  # percentage of words to be randomly inserted
  alpha_rs: 0.1  # percentage of words to be randomly swapped
  p_rd: 0.1      # probability of word deletion
  num_aug: 9     # number of augmented sentences to generate per original sentence

training_params:
  learning_rate: 1e-4
  batch_size: 32
  num_epochs: 10

model:
  vocab_size: 30522
  embed_size: 768
  num_heads: 12
  hidden_dim: 3072
  num_layers: 12
  num_classes: 2
  dropout: 0.1
  max_len: 128

evaluation:
  save_best_model_path: '/Users/admin/Desktop/synnergy_network/pkg/synnergy_network/core/ai_machine_learning/ai_conversation_bot/models/best_model.pth'



