# Configuration file for Synnergy Network Regulatory Node

[network]
# Network settings for the node
node_id = "regulatory-node-01"
network_id = "synnergy-mainnet"
port = 30303
bootnodes = ["enode://bootnode1@ip1:port1", "enode://bootnode2@ip2:port2"]

[security]
# Security settings for the node
encryption_method = "AES" # Options: AES, Scrypt, Argon2, RSA, ECC
encryption_key = "your-secure-encryption-key" # Replace with your actual encryption key
use_multi_sig = true
required_signatures = 3

[compliance]
# Compliance settings for the regulatory node
enable_aml_monitoring = true
aml_threshold = 10000 # Amount in Synthron coin above which transactions are flagged for AML
enable_kyc_verification = true
kyc_service_url = "https://kycservice.example.com"
enable_auto_reporting = true
reporting_service_url = "https://reportingservice.example.com"
audit_interval = 86400 # Time in seconds for regular transaction audits

[storage]
# Storage settings for blockchain data
data_dir = "/var/synnergy/data"
log_dir = "/var/synnergy/logs"
backup_dir = "/var/synnergy/backups"
max_storage_size_gb = 500

[consensus]
# Consensus settings for the node
consensus_algorithm = "PoW-PoS-PoH"
pow_difficulty = 4000
pos_stake_min = 1000 # Minimum stake required in Synthron coin
poh_interval = 600 # Interval in seconds for Proof of History

[api]
# API settings for the node
enable_api = true
api_host = "0.0.0.0"
api_port = 8080
enable_tls = true
tls_cert_file = "/path/to/tls_cert.pem"
tls_key_file = "/path/to/tls_key.pem"

[alerts]
# Alert settings for monitoring and notifications
enable_alerts = true
alert_service_url = "https://alertservice.example.com"
alert_thresholds = {
    "high_cpu_usage" = 80,    # Alert when CPU usage exceeds 80%
    "high_memory_usage" = 75, # Alert when Memory usage exceeds 75%
    "low_disk_space" = 10     # Alert when disk space is below 10%
}

[backup]
# Backup settings
enable_automatic_backups = true
backup_frequency = 86400 # Time in seconds for regular backups
backup_encryption = "AES" # Options: AES, Scrypt, Argon2

[logging]
# Logging settings
log_level = "info" # Options: debug, info, warn, error
log_file = "/var/synnergy/logs/regulatory_node.log"

[updates]
# Settings for automatic updates
enable_auto_updates = true
update_check_interval = 86400 # Time in seconds to check for updates

[monitoring]
# Monitoring settings for the node
enable_health_checks = true
health_check_interval = 300 # Interval in seconds for health checks
health_check_service_url = "https://healthcheckservice.example.com"

[risk_management]
# Risk management settings
enable_risk_assessment = true
risk_assessment_service_url = "https://riskassessment.example.com"
incident_response_plan = "/path/to/incident_response_plan.pdf"

# Example values and should be replaced with actual configurations for deployment
