# Lightning Node Configuration File

# [General] section covers general settings for the node.
[General]
# The name of the node.
node_name = "synthron_lightning_node"

# The version of the node software.
version = "1.0.0"

# [Network] section covers network-related settings.
[Network]
# The host and port on which the node listens for incoming connections.
host = "0.0.0.0"
port = 9735

# The list of peers to connect to.
peers = [
    "peer1.synthron.org:9735",
    "peer2.synthron.org:9735"
]

# The maximum number of concurrent connections.
max_connections = 100

# [Channels] section covers settings related to payment channels.
[Channels]
# The base fee for transactions (in satoshis).
base_fee = 1000

# The fee rate for transactions (in satoshis per million).
fee_rate = 1

# The minimum and maximum allowed channel capacity (in satoshis).
min_channel_capacity = 100000
max_channel_capacity = 10000000

# The interval for rebalancing channels (in seconds).
rebalance_interval = 3600

# [Security] section covers security-related settings.
[Security]
# Path to the private key file.
private_key_file = "/path/to/private.key"

# Path to the public key file.
public_key_file = "/path/to/public.key"

# Encryption algorithm to use (options: "scrypt", "aes", "argon2").
encryption_algorithm = "argon2"

# Whether to use salts for encryption.
use_salts = true

# Path to the HSM (Hardware Security Module) configuration file.
hsm_config_file = "/path/to/hsm/config.toml"

# [Logging] section covers logging-related settings.
[Logging]
# Path to the log file.
log_file = "/var/log/synthron_lightning_node.log"

# Log level (options: "debug", "info", "warn", "error").
log_level = "info"

# [Monitoring] section covers settings for monitoring and alerting.
[Monitoring]
# Whether to enable real-time monitoring.
enable_monitoring = true

# Monitoring server host and port.
monitoring_host = "monitoring.synthron.org"
monitoring_port = 9090

# Alert thresholds for various metrics (e.g., CPU usage, memory usage).
alert_thresholds = { cpu = 80, memory = 70 }

# [Database] section covers settings for the node's database.
[Database]
# Path to the database file.
db_file = "/path/to/database.db"

# Database backup interval (in seconds).
backup_interval = 86400

# Maximum size of the database (in MB).
max_db_size = 1000

# [Performance] section covers settings to optimize performance.
[Performance]
# Number of worker threads for processing transactions.
worker_threads = 8

# Whether to enable transaction batching.
enable_batching = true

# Batch size for transactions.
batch_size = 100

# [Compliance] section covers compliance and audit settings.
[Compliance]
# Whether to enable compliance checks.
enable_compliance = true

# Path to the compliance rules file.
compliance_rules_file = "/path/to/compliance/rules.toml"

# Audit interval (in seconds).
audit_interval = 604800

# [Backup] section covers settings for data backup and recovery.
[Backup]
# Path to the backup directory.
backup_dir = "/path/to/backup"

# Backup frequency (in seconds).
backup_frequency = 43200

# Retention period for backups (in seconds).
backup_retention = 2592000

# [API] section covers API settings for node management.
[API]
# Whether to enable the API.
enable_api = true

# API server host and port.
api_host = "0.0.0.0"
api_port = 8080

# API access token for authentication.
api_access_token = "your_api_access_token"

# [Notification] section covers settings for notifications.
[Notification]
# Whether to enable notifications.
enable_notifications = true

# Notification endpoints (e.g., email, webhook).
notification_endpoints = [
    "email:alerts@synthron.org",
    "webhook:https://webhook.synthron.org/alerts"
]

# [Maintenance] section covers scheduled maintenance settings.
[Maintenance]
# Maintenance window (start and end time in HH:MM format).
maintenance_window = { start = "02:00", end = "03:00" }

# Maintenance tasks to run during the maintenance window.
maintenance_tasks = [
    "reindex_database",
    "clean_logs"
]

# [Debug] section covers settings for debugging and troubleshooting.
[Debug]
# Whether to enable debug mode.
enable_debug = false

# Path to the debug logs directory.
debug_logs_dir = "/path/to/debug/logs"

# Maximum size of debug logs (in MB).
max_debug_log_size = 500
