# Configuration for Synthron Light Node

[light_node]
# Node Identity
node_id = "synthron-light-node-001"
node_name = "Synthron Light Node 1"

# Network Configuration
[network]
# The address and port this node listens on for incoming connections
listen_address = "0.0.0.0:8080"

# The address of the trusted full node to connect to for block and transaction data
trusted_full_node_address = "fullnode.synthron.network:8080"

# The number of block headers to cache locally
block_header_cache_size = 1000

# Intermittent connectivity settings
# Synchronize data every X seconds
sync_interval = 600  # in seconds, here it syncs every 10 minutes

# Enable secure communication channels
tls_cert_file = "/path/to/tls_cert.pem"
tls_key_file = "/path/to/tls_key.pem"
tls_ca_cert_file = "/path/to/ca_cert.pem"

# Hardware and Performance Settings
[performance]
# Maximum CPU usage percentage
max_cpu_usage = 50  # in percentage

# Memory usage limit in MB
max_memory_usage = 2048  # in MB (2 GB)

# Storage configuration
storage_path = "/var/lib/synthron/lightnode"
max_storage_size = 20480  # in MB (20 GB)

# Logging Configuration
[logging]
# Logging level: trace, debug, info, warn, error, fatal
log_level = "info"
log_file = "/var/log/synthron/lightnode.log"
log_max_size = 100  # Max size in MB before log rotation
log_max_backups = 10  # Max number of rotated log files to keep
log_max_age = 30  # Max age in days before log file is deleted

# Security Configuration
[security]
# End-to-end encryption settings
encryption_algorithm = "aes-256-gcm"
encryption_key = "your-32-byte-long-encryption-key-goes-here"  # Must be 32 bytes for AES-256

# Biometric access control settings
biometric_enabled = false
biometric_device = "/dev/biometric"

# Monitoring and Auditing
[monitoring]
# Real-time monitoring settings
enable_real_time_monitoring = true
monitoring_endpoint = "https://monitoring.synthron.network"
monitoring_api_key = "your-monitoring-api-key-here"

# Audit settings
audit_interval = 86400  # in seconds, here it audits every 24 hours
audit_log_file = "/var/log/synthron/audit.log"

# Compliance settings
compliance_check_enabled = true
compliance_standards = ["ISO27001", "GDPR"]
compliance_report_path = "/var/lib/synthron/compliance/reports"

# Integration Settings
[integration]
# API settings for integrating with other applications and services
api_enabled = true
api_listen_address = "0.0.0.0:8090"
api_tls_cert_file = "/path/to/api_tls_cert.pem"
api_tls_key_file = "/path/to/api_tls_key.pem"

# Notifications settings
notifications_enabled = true
notifications_endpoint = "https://notifications.synthron.network"
notifications_api_key = "your-notifications-api-key-here"

# User-defined settings for further custom configurations
[user_defined]
custom_setting1 = "value1"
custom_setting2 = "value2"

# End of configuration
