# AI-Enhanced Node Configuration File

# General node settings
[node]
id = "ai_enhanced_node_1"  # Unique identifier for this AI-enhanced node
name = "AI Enhanced Node"  # Human-readable name for the node
network = "mainnet"       # Network the node is part of (e.g., mainnet, testnet)
log_level = "info"        # Log level (e.g., debug, info, warn, error)

# Networking settings
[network]
port = 8080               # Port for node communication
max_connections = 100     # Maximum number of peer connections
heartbeat_interval = 60   # Interval (in seconds) for sending heartbeat messages to peers

# AI settings
[ai]
model_path = "/app/data/models"       # Path to the directory containing AI models
training_data_path = "/app/data/training"  # Path to the directory containing training data
prediction_interval = 30             # Interval (in seconds) for running AI predictions
model_update_interval = 86400        # Interval (in seconds) for updating AI models

# AI Hardware settings
[ai.hardware]
gpu_enabled = true       # Whether to use GPU for AI computations
tpu_enabled = false      # Whether to use TPU for AI computations
max_gpu_memory = "16GB"  # Maximum GPU memory to use
max_tpu_memory = "16GB"  # Maximum TPU memory to use

# Data storage settings
[storage]
data_dir = "/app/data"            # Directory for storing blockchain data
logs_dir = "/app/logs"            # Directory for storing log files
backup_dir = "/app/data/backup"   # Directory for storing data backups
max_storage_size = "500GB"        # Maximum storage size for blockchain data

# Security settings
[security]
encryption_method = "argon2"  # Encryption method to use (e.g., scrypt, aes, argon2)
use_salts = true              # Whether to use salts in encryption
access_control_enabled = true  # Whether access control is enabled

# Access control settings
[security.access_control]
admin_users = ["admin1", "admin2"]  # List of admin users with full access
read_only_users = ["user1", "user2"] # List of read-only users

# API settings
[api]
enabled = true                # Whether the API is enabled
bind_address = "0.0.0.0"      # Address to bind the API to
port = 8081                   # Port for the API
api_key = "your_secure_api_key_here" # API key for accessing the node's API

# AI Ethics and Compliance settings
[ai.ethics]
ethical_use_framework = true  # Whether to adhere to ethical AI use framework
privacy_protection = true     # Whether to ensure privacy protection
gdpr_compliance = true        # Whether to comply with GDPR

# Logging settings
[logging]
level = "info"               # Logging level (e.g., debug, info, warn, error)
log_to_file = true           # Whether to log to a file
log_file_path = "/app/logs/ai_node.log" # Path to the log file
max_log_size = "100MB"       # Maximum size of log files before rotation
log_rotation_count = 5       # Number of rotated log files to keep

# Update settings
[updates]
auto_update_enabled = true   # Whether to enable automatic updates
update_check_interval = 43200 # Interval (in seconds) for checking updates

# Health check settings
[health_check]
enabled = true                 # Whether health checks are enabled
check_interval = 300           # Interval (in seconds) for health checks
health_check_url = "http://localhost:8081/health" # URL for health check endpoint

# Model Training and Validation settings
[ai.training]
training_enabled = true        # Whether model training is enabled
training_interval = 86400      # Interval (in seconds) for training models
validation_enabled = true      # Whether model validation is enabled
validation_interval = 86400    # Interval (in seconds) for validating models

# Advanced settings
[advanced]
experimental_features = false  # Whether to enable experimental features
