# Historical Node Configuration File

[server]
# The host and port for the Historical Node server to listen on.
host = "0.0.0.0"
port = 8080

[database]
# Configuration for the database storing historical data.
type = "postgres"
host = "localhost"
port = 5432
name = "historical_data"
user = "dbuser"
password = "dbpassword"

[storage]
# Configuration for storage solutions.
# Path to the data directory for storing blockchain data.
data_directory = "/data/blockchain"
backup_directory = "/backups/blockchain"
# Storage capacity settings
max_storage_gb = 1000
backup_interval_hours = 24

[security]
# Security configurations for encryption and access control.
# Encryption settings
encryption_method = "AES"
encryption_key = "your-encryption-key"
# Authentication and Access Control
auth_method = "jwt"
jwt_secret = "your-jwt-secret"
# Enable/disable multi-factor authentication
enable_mfa = true

[network]
# Network settings for communication with other nodes.
# Use secure channels for node communication.
use_tls = true
tls_cert_file = "/path/to/tls_cert.pem"
tls_key_file = "/path/to/tls_key.pem"

[logging]
# Logging configurations.
# Log levels: debug, info, warn, error
log_level = "info"
log_file = "/logs/historical_node.log"
# Log rotation settings
log_rotation_days = 7
log_max_size_mb = 100

[monitoring]
# Monitoring and alerting settings.
# Endpoint for monitoring system
monitoring_endpoint = "http://localhost:9090"
# Alert settings
enable_alerts = true
alert_recipients = ["admin@example.com"]
alert_thresholds = { cpu_usage = 80, memory_usage = 80, disk_usage = 90 }

[backup]
# Backup settings for redundancy and data integrity.
# Backup intervals and retention policy
interval_hours = 12
retention_days = 30
# Backup destinations
local_backup_path = "/backups/local"
remote_backup_path = "s3://your-s3-bucket/backups"

[performance]
# Performance tuning parameters.
# Thread and connection settings
max_threads = 8
max_connections = 100
# Cache settings
enable_caching = true
cache_size_mb = 512
cache_expiry_minutes = 60

[api]
# API settings for external access.
# Enable/disable the API
enable_api = true
# API endpoint and rate limiting
api_endpoint = "http://localhost:8080/api"
rate_limit_per_minute = 100

# Compliance and audit settings
[compliance]
# Data retention policy
retention_period_years = 7
# Audit log settings
audit_log_file = "/logs/audit.log"
audit_log_rotation_days = 30
