# Pruned Full Node Configuration

# Network settings
[network]
# Address to bind to for listening for peer connections
listen_address = "0.0.0.0:8545"
# Address of the bootstrap nodes for initial network discovery
bootstrap_nodes = [
    "node1.synthron.network:8545",
    "node2.synthron.network:8545"
]
# Maximum number of inbound and outbound peers
max_peers = 50

# Logging settings
[logging]
# Log level: trace, debug, info, warn, error
level = "info"
# Log file location
file = "/var/log/pruned_full_node.log"

# Storage settings
[storage]
# Path to store blockchain data
path = "/data/pruned_full_node"
# Pruning settings to keep the storage optimized
prune_blocks_older_than = 100000
# Interval in blocks to run the pruning process
prune_interval = 1000

# Consensus settings
[consensus]
# Consensus algorithm to use
algorithm = "argon2"
# Path to consensus state file
state_file = "/data/consensus_state"

# Security settings
[security]
# Enable TLS for network communication
enable_tls = true
# Paths to the TLS certificate and key
tls_cert_file = "/etc/synthron/tls/cert.pem"
tls_key_file = "/etc/synthron/tls/key.pem"
# Enable multi-factor authentication for node access
enable_mfa = true
# Path to the MFA configuration file
mfa_config_file = "/etc/synthron/mfa_config.json"

# Performance settings
[performance]
# Maximum number of concurrent threads
max_threads = 8
# Cache settings to optimize node performance
cache_size = "2GB"

# Monitoring and maintenance settings
[monitoring]
# Enable health check endpoint
enable_health_check = true
# Health check endpoint address
health_check_address = "0.0.0.0:8080"
# Enable metrics collection
enable_metrics = true
# Metrics collection endpoint
metrics_endpoint = "0.0.0.0:9090"

# Backup settings
[backup]
# Path to store backup data
backup_path = "/data/backup"
# Frequency of backups (daily, weekly, monthly)
backup_frequency = "daily"
# Retention period for backups (in days)
backup_retention_days = 30

# Incentive settings
[incentives]
# Enable incentive structures for running a pruned full node
enable_incentives = true
# Reward per validated block
reward_per_block = 10.0
# Bonus for maintaining uptime over a period (percentage)
uptime_bonus_percentage = 5.0

# Additional features
[features]
# Enable historical data access
enable_historical_data = true
# Path to store historical data
historical_data_path = "/data/historical"

# Debug settings
[debug]
# Enable debug mode
enable_debug = false
# Debug log level
debug_log_level = "debug"

# Notifications settings
[notifications]
# Enable notifications for critical events
enable_notifications = true
# Notification endpoint
notification_endpoint = "http://notifications.synthron.network:8000"

# Update settings
[updates]
# Auto-update enabled
auto_update = true
# Update check interval (in hours)
update_check_interval = 24

# Application-specific settings
[app]
# Node name for identification
node_name = "PrunedFullNode1"
# Operator email for contact
operator_email = "operator@synthron.network"
