# Hybrid Node Configuration File

[general]
# Node ID uniquely identifies this node within the blockchain network
node_id = "hybrid-node-01"

# Node type
node_type = "hybrid"

# Log level for the node operations (trace, debug, info, warn, error)
log_level = "info"

# Path to store node data
data_path = "/var/lib/synthron/hybrid_node/data"

# Path to store node logs
log_path = "/var/log/synthron/hybrid_node"

[network]
# Network configurations
network_interface = "0.0.0.0"
network_port = 8080

# Encryption key for secure communication
encryption_key = "path/to/encryption_key.pem"

[consensus]
# Consensus configurations
consensus_algorithm = "argon2"
block_proposal_interval = "10s"

[resources]
# Resource allocation for dynamic management
cpu_limit = "4"
memory_limit = "16GB"
storage_limit = "1TB"

[security]
# Security protocols and measures
use_scrypt = true
use_aes = true
use_argon2 = true

# Salt for encryption (if needed)
encryption_salt = "random_salt_value"

# End-to-end encryption settings
e2e_encryption = true

[database]
# Database configurations for indexing and query handling
db_host = "localhost"
db_port = 5432
db_user = "synthron_user"
db_password = "synthron_password"
db_name = "synthron_db"

[monitoring]
# Monitoring configurations
enable_monitoring = true
monitoring_port = 9090
health_check_interval = "30s"

[backup]
# Backup strategies for redundancy and data recovery
enable_backup = true
backup_interval = "24h"
backup_path = "/var/backups/synthron/hybrid_node"

[audit]
# Audit and logging settings
enable_audit_logs = true
audit_log_path = "/var/log/synthron/hybrid_node/audit"

[alerts]
# Alert configurations for proactive notifications
enable_alerts = true
alert_email = "admin@synthron.org"
alert_thresholds = { cpu_usage = "80%", memory_usage = "80%", disk_usage = "90%" }

[performance]
# Performance optimization settings
enable_auto_tuning = true
performance_profile = "high"

[ui]
# User Interface settings for management and monitoring
enable_ui = true
ui_port = 3000
ui_path = "/usr/share/synthron/hybrid_node/ui"
