# Mining Node Configuration for Synthron Blockchain

[network]
# Network settings for connecting to the Synthron blockchain network
network_id = "synthron-mainnet"
listen_ip = "0.0.0.0"
listen_port = 30303
max_peers = 50

[mining]
# Mining-specific settings
mining_enabled = true
miner_address = "0xYourMinerAddressHere" # Replace with your actual miner address
threads = 4 # Number of CPU threads to use for mining
difficulty_target = "0x00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" # Initial difficulty target

[hardware]
# Hardware settings for optimizing mining performance
gpu_enabled = true
gpu_devices = [0, 1] # List of GPU devices to use for mining
gpu_memory_clock = 7000 # GPU memory clock in MHz
gpu_core_clock = 1500 # GPU core clock in MHz
gpu_power_limit = 250 # GPU power limit in watts
asic_enabled = false # Enable if using ASIC devices for mining

[storage]
# Storage settings for managing blockchain data
data_dir = "/var/lib/synthron/mining_node/data"
cache_size = 2048 # Cache size in MB
prune_blocks = true # Enable block pruning to save storage space
prune_blocks_keep_recent = 10000 # Number of recent blocks to keep

[security]
# Security settings to protect the mining node
use_vpn = true
vpn_address = "vpn.synthron.io" # VPN server address
firewall_enabled = true
firewall_rules = [
  "allow from 192.168.0.0/16",
  "allow from 10.0.0.0/8",
  "deny all"
]

[logging]
# Logging settings for monitoring and debugging
log_dir = "/var/log/synthron/mining_node"
log_level = "info" # Available levels: debug, info, warn, error
log_rotation = "daily" # Log rotation policy: daily, weekly, monthly

[performance]
# Performance tuning settings
max_cpu_usage = 85 # Max CPU usage percentage
max_memory_usage = 90 # Max memory usage percentage
auto_tune = true # Enable automatic tuning of hardware settings

[incentives]
# Economic incentives and reward structures
block_reward = 12.5 # Initial block reward in Synthron tokens
block_reward_halving_interval = 210000 # Number of blocks before block reward is halved
transaction_fee_percentage = 0.1 # Percentage of transaction fees collected by miners

[backup]
# Backup and disaster recovery settings
backup_enabled = true
backup_interval = "24h" # Backup interval: 24h, 12h, 6h, etc.
backup_location = "/mnt/backup/synthron/mining_node"

[api]
# API settings for remote management and monitoring
api_enabled = true
api_listen_ip = "127.0.0.1"
api_listen_port = 8545
api_access_token = "your_api_access_token_here"

[alerts]
# Alert settings for monitoring and notifications
alert_enabled = true
alert_email = "admin@synthron.io"
alert_threshold_cpu = 90 # CPU usage percentage threshold for alerts
alert_threshold_memory = 95 # Memory usage percentage threshold for alerts
alert_threshold_temp = 85 # Temperature threshold for alerts in Celsius
