before putting into the main.go file manage the token standards so it is like a funnel and easier to manage :
Connect in use of tokens and deployment and creation of tokens, deployment, management, storage events :
"synthron-blockchain/pkg/token_standards/syn20"
    "synthron-blockchain/pkg/token_standards/syn130"
    "synthron-blockchain/pkg/token_standards/syn131"
    "synthron-blockchain/pkg/token_standards/syn223"
    "synthron-blockchain/pkg/token_standards/syn721"
    "synthron-blockchain/pkg/token_standards/syn722"
    "synthron-blockchain/pkg/token_standards/syn845"
    "synthron-blockchain/pkg/token_standards/syn1155"
    "synthron-blockchain/pkg/token_standards/syn1401"
    "synthron-blockchain/pkg/token_standards/syn1967"
    "synthron-blockchain/pkg/token_standards/syn2369"
    "synthron-blockchain/pkg/token_standards/syn70"
    "synthron-blockchain/pkg/token_standards/syn300"
    "synthron-blockchain/pkg/token_standards/syn500"
    "synthron-blockchain/pkg/token_standards/syn600"
    "synthron-blockchain/pkg/token_standards/syn800"
    "synthron-blockchain/pkg/token_standards/syn900"
    "synthron-blockchain/pkg/token_standards/syn1000"
    "synthron-blockchain/pkg/token_standards/syn1200"
    "synthron-blockchain/pkg/token_standards/syn1500"
    "synthron-blockchain/pkg/token_standards/syn200"
    "synthron-blockchain/pkg/token_standards/syn700"
    "synthron-blockchain/pkg/token_standards/syn1100"
    "synthron-blockchain/pkg/token_standards/syn1300"
    "synthron-blockchain/pkg/token_standards/syn1600"
    "synthron-blockchain/pkg/token_standards/syn1700"
    "synthron-blockchain/pkg/token_standards/syn1800"
    "synthron-blockchain/pkg/token_standards/syn1900"
    "synthron-blockchain/pkg/token_standards/syn2100"
    "synthron-blockchain/pkg/token_standards/syn2200"
    "synthron-blockchain/pkg/token_standards/syn2400"
    "synthron-blockchain/pkg/token_standards/syn2500"
    "synthron-blockchain/pkg/token_standards/syn2600"
    "synthron-blockchain/pkg/token_standards/syn2700"
    "synthron-blockchain/pkg/token_standards/syn2800"
    "synthron-blockchain/pkg/token_standards/syn2900"
    "synthron-blockchain/pkg/token_standards/syn3000"
    "synthron-blockchain/pkg/token_standards/syn3100"
    "synthron-blockchain/pkg/token_standards/syn3200"
    "synthron-blockchain/pkg/token_standards/syn3300"
    "synthron-blockchain/pkg/token_standards/syn3400"
    "synthron-blockchain/pkg/token_standards/syn3500"
    "synthron-blockchain/pkg/token_standards/syn3600"
    "synthron-blockchain/pkg/token_standards/syn3700"
    "synthron-blockchain/pkg/token_standards/syn3800"
    "synthron-blockchain/pkg/token_standards/syn3900"
    "synthron-blockchain/pkg/token_standards/syn4200"
    "synthron-blockchain/pkg/token_standards/syn4300"
    "synthron-blockchain/pkg/token_standards/syn4700"
    "synthron-blockchain/pkg/token_standards/syn4900"
    "synthron-blockchain/pkg/token_standards/syn5000"


	add: /Users/admin/Desktop/synthron_blockchain_final/pkg/tokens/token_creation_deployment