# Watchtower Node Configuration

# General settings
[general]
node_name = "synthron_watchtower"
log_level = "info"  # Log levels: debug, info, warn, error
data_dir = "/var/lib/synthron/watchtower/data"
log_dir = "/var/lib/synthron/watchtower/logs"
port = 8080

# Network settings
[network]
listen_address = "0.0.0.0"
public_address = "your_public_ip_or_domain"
max_connections = 1000
max_bandwidth = "1Gbps"  # Adjust according to your network capabilities

# Security settings
[security]
enable_tls = true
tls_cert_file = "/etc/synthron/certs/watchtower_cert.pem"
tls_key_file = "/etc/synthron/certs/watchtower_key.pem"
enable_firewall = true
firewall_rules = ["allow 8080/tcp", "allow 8443/tcp", "deny all"]

# Authentication settings
[authentication]
enable_mfa = true
mfa_provider = "google_authenticator"
authorized_users = ["admin", "operator"]
access_control_list = "/etc/synthron/access_control_list"

# Encryption settings
[encryption]
use_scrypt = true
scrypt_n = 16384  # Cost factor
scrypt_r = 8      # Block size factor
scrypt_p = 1      # Parallelization factor
use_aes = true
aes_key_length = 256  # AES key length in bits

# Monitoring and alerting
[monitoring]
enable_monitoring = true
monitoring_interval = 60  # in seconds
alert_email = "admin@synthron.org"
alert_thresholds = { cpu_usage = 90, memory_usage = 80, disk_usage = 90 }

# Database settings
[database]
db_type = "postgresql"  # Options: postgresql, mysql, sqlite
db_host = "127.0.0.1"
db_port = 5432
db_name = "synthron_watchtower"
db_user = "watchtower_user"
db_password = "secure_password"
connection_pool_size = 20

# Logging settings
[logging]
log_to_file = true
log_to_console = true
log_file_max_size = "100MB"
log_file_max_age = 30  # in days
log_file_max_backups = 10

# Orphan block management
[orphan_block]
detection_interval = 30  # in seconds
max_orphan_blocks = 100
archive_orphan_blocks = true
archive_dir = "/var/lib/synthron/watchtower/orphan_archive"

# Smart contract enforcement
[smart_contract]
enable_contract_enforcement = true
contract_rules_file = "/etc/synthron/contract_rules.json"

# Lightning Network channel management
[lightning_network]
enable_ln_channel_guardianship = true
ln_channel_monitoring_interval = 10  # in seconds

# Proactive alert systems
[proactive_alerts]
enable_proactive_alerts = true
alert_prediction_algorithm = "complex_algo_v2"
alert_log_file = "/var/lib/synthron/watchtower/alerts.log"

# Advanced settings
[advanced]
cpu_affinity = [0, 1, 2, 3]  # Pinning process to specific CPU cores
memory_allocation = "16GB"   # Allocating specific amount of RAM

# Backup and recovery settings
[backup_recovery]
enable_backup = true
backup_interval = "24h"
backup_dir = "/var/lib/synthron/watchtower/backups"
restore_last_backup_on_failure = true

# Compliance and audit settings
[compliance]
enable_compliance_checks = true
audit_log_dir = "/var/lib/synthron/watchtower/audit_logs"
audit_check_interval = "7d"

# API settings
[api]
enable_api = true
api_listen_address = "0.0.0.0"
api_port = 8443
api_rate_limit = 100  # requests per second

# End of configuration file
