# Configuration for Disaster Recovery Node in Synnergy Network

[node]
# General Node Configuration
node_id = "disaster_recovery_node_1"
node_type = "disaster_recovery"
network_id = "synnergy_mainnet"
listen_address = "0.0.0.0:8080"
log_level = "info"
data_dir = "/app/data"
backup_dir = "/app/backups"

[security]
# Security Configurations
encryption_algorithm = "AES256"  # Options: AES256, RSA, ECC
key_derivation_algorithm = "Scrypt"  # Options: Scrypt, Argon2
use_salts = true
salts_dir = "/app/salts"

[backup]
# Backup Configuration
backup_interval_minutes = 60  # Interval for backups in minutes
incremental_backup = true
retention_period_days = 30  # Retain backups for 30 days
geographical_redundancy = true
backup_locations = ["us-west", "eu-central", "ap-southeast"]

[recovery]
# Recovery Configuration
enable_auto_recovery = true
max_recovery_time_minutes = 30  # Maximum time allowed for automatic recovery
disaster_recovery_drills_interval_days = 7  # Interval for disaster recovery drills

[network]
# Network Configuration
max_peers = 50
bootstrap_nodes = [
    "node1.synnergy.network:8080",
    "node2.synnergy.network:8080"
]
use_tls = true
tls_cert_file = "/app/certs/tls.crt"
tls_key_file = "/app/certs/tls.key"

[consensus]
# Consensus Configuration
consensus_algorithm = "PoH"  # Options: PoW, PoS, PoH
pow_algorithm = "argon2"
pos_stake_threshold = 1000  # Minimum stake for PoS
poh_history_length = 10000  # Number of blocks to consider for PoH

[ai_anomaly_detection]
# AI-Powered Anomaly Detection Configuration
enable_ai_detection = true
ai_model_path = "/app/models/anomaly_detection_model"
detection_threshold = 0.95

[sharding]
# Blockchain Data Sharding Configuration
enable_sharding = true
shard_count = 10
shard_storage_dir = "/app/shards"

[self_healing]
# Self-Healing Mechanisms Configuration
enable_self_healing = true
healing_interval_minutes = 10  # Interval for self-healing checks
corruption_threshold = 0.1  # Threshold for corruption detection (10%)

[logging]
# Logging Configuration
log_to_file = true
log_file_path = "/app/logs/disaster_recovery_node.log"
log_rotation = "daily"
max_log_size_mb = 100
log_retention_days = 7

[monitoring]
# Monitoring and Metrics Configuration
enable_monitoring = true
monitoring_address = "0.0.0.0:9100"
metrics_collection_interval_seconds = 60
